### ISSUE TITLE
Update Preprocessor json dump to use concrete transformer

### ISSUE THREAD

**Issue by jichaogp** [georgianpartners/foreshadow#53]
#### Description

According to the discussion in #51, update the code so that the preprocessor json dump include concrete transformer instead of smart transformer.

**Comment by robocoder99** [comment]
@jichaogp @adithyabsk I have encountered a small roadblock here considering serializing pipelines intended for **intent pipeline overrides** in the JSON. These pipelines are not fit as they are slotted into intent pipelines as an override when one in the JSON doesn't exist for a specific column. So the smart transformer has not resolved into a true transformer. 

In my opinion it is best to simply serialize it into a smart transformer in this case. I wanted to check with y'all though since this impacts the scope of the issue (i.e. there are cases in which a serialized pipeline could have smart transformers).

**Comment by robocoder99** [comment]
Closing issue per pull request #54
